In [4]:
import pandas as pd
import statistics as stat

filepath = '/content/AI On-Campus Research Survey (Responses).csv'
loadFile = pd.read_csv(filepath)


dataFrame = pd.DataFrame(loadFile)
dataFrame

,Timestamp,"On a scale from 1 to 5, how would you rate your knowledge and understanding of Artificial Intelligence (AI)?","On a scale from 1 to 5, how often do you use Artificial Intelligence (AI) for personal use?","On a scale from 1 to 5, how often do you use Artificial Intelligence (AI) for school-related tasks?","On a scale from 1 to 5, how interested are you in pursuing a career in Artificial Intelligence?",Do you know what Chat-GPT is?,What college are you in?
0,3/31/2023 19:59:11,5,5,5,5,Yes,"Science, Engineering, & Technology"
1,3/31/2023 19:59:45,4,3,4,4,Yes,"Science, Engineering, & Technology"
2,3/31/2023 20:06:25,3,3,5,1,No,Business
3,3/31/2023 20:10:55,4,3,5,2,Yes,Business
4,3/31/2023 20:14:34,5,2,1,5,Yes,Humanities & Social Sciences
...,...,...,...,...,...,...,...
253,10/24/2023 14:02:44,5,2,3,3,Yes,"Science, Engineering, & Technology"
254,10/24/2023 14:22:30,4,3,2,2,Yes,Arts & Media
255,10/25/2023 10:08:07,4,3,3,2,Yes,"Science, Engineering, & Technology"
256,11/6/2023 8:52:21,4,3,2,2,Yes,"Science, Engineering, & Technology"
257,1/25/2024 14:51:11,4,2,2,2,Yes,"Science, Engineering, & Technology"

In [8]:
#Identify Columns
print(dataFrame.columns.tolist())

['Timestamp', 'On a scale from 1 to 5, how would you rate your knowledge and understanding of Artificial Intelligence (AI)?', 'On a scale from 1 to 5, how often do you use Artificial Intelligence (AI) for personal use?', 'On a scale from 1 to 5, how often do you use Artificial Intelligence (AI) for school-related tasks?', 'On a scale from 1 to 5, how interested are you in pursuing a career in Artificial Intelligence?', 'Do you know what Chat-GPT is?', 'What college are you in?']

In [10]:
#Take a sample from the data set
dataFrame[:20]

,Timestamp,"On a scale from 1 to 5, how would you rate your knowledge and understanding of Artificial Intelligence (AI)?","On a scale from 1 to 5, how often do you use Artificial Intelligence (AI) for personal use?","On a scale from 1 to 5, how often do you use Artificial Intelligence (AI) for school-related tasks?","On a scale from 1 to 5, how interested are you in pursuing a career in Artificial Intelligence?",Do you know what Chat-GPT is?,What college are you in?
0,3/31/2023 19:59:11,5,5,5,5,Yes,"Science, Engineering, & Technology"
1,3/31/2023 19:59:45,4,3,4,4,Yes,"Science, Engineering, & Technology"
2,3/31/2023 20:06:25,3,3,5,1,No,Business
3,3/31/2023 20:10:55,4,3,5,2,Yes,Business
4,3/31/2023 20:14:34,5,2,1,5,Yes,Humanities & Social Sciences
5,3/31/2023 20:56:01,2,1,1,1,No,Nursing & Health Care
6,3/31/2023 21:02:52,2,1,1,1,Yes,Humanities & Social Sciences
7,3/31/2023 21:10:58,3,2,1,1,Yes,"Science, Engineering, & Technology"
8,3/31/2023 21:13:52,3,3,3,1,No,"Science, Engineering, & Technology"
9,3/31/2023 21:24:05,2,2,1,1,Yes,"Science, Engineering, & Technology"
10,3/31/2023 22:28:49,3,1,1,1,Yes,Arts & Media
11,3/31/2023 22:34:16,3,2,1,2,Yes,Humanities & Social Sciences
12,3/31/2023 22:35:06,3,2,1,2,Yes,Humanities & Social Sciences
13,3/31/2023 22:48:46,3,1,1,1,Yes,Nursing & Health Care
14,3/31/2023 23:37:58,3,1,1,1,Yes,Humanities & Social Sciences
15,3/31/2023 23:44:34,2,2,1,3,Yes,"Science, Engineering, & Technology"
16,4/1/2023 0:16:47,4,2,1,1,Yes,Nursing & Health Care
17,4/1/2023 4:08:57,1,1,1,1,No,Nursing & Health Care
18,4/1/2023 9:15:14,2,2,2,1,No,Nursing & Health Care
19,4/1/2023 10:36:40,3,3,3,2,Yes,"Science, Engineering, & Technology"

In [12]:
#Take last 20 elements
dataFrame.tail(20)

,Timestamp,"On a scale from 1 to 5, how would you rate your knowledge and understanding of Artificial Intelligence (AI)?","On a scale from 1 to 5, how often do you use Artificial Intelligence (AI) for personal use?","On a scale from 1 to 5, how often do you use Artificial Intelligence (AI) for school-related tasks?","On a scale from 1 to 5, how interested are you in pursuing a career in Artificial Intelligence?",Do you know what Chat-GPT is?,What college are you in?
238,4/25/2023 15:16:49,2,1,1,1,Yes,Business
239,4/26/2023 9:50:55,4,3,3,4,Yes,Humanities & Social Sciences
240,4/26/2023 10:48:29,4,2,3,1,Yes,Business
241,4/26/2023 12:12:55,3,1,1,1,Yes,Education
242,4/26/2023 13:13:44,3,1,1,1,Yes,Theology
243,4/27/2023 19:33:06,3,3,1,1,Yes,Humanities & Social Sciences
244,5/31/2023 13:51:38,3,2,2,1,Yes,"Science, Engineering, & Technology"
245,9/2/2023 14:02:38,3,1,1,1,Yes,"Science, Engineering, & Technology"
246,9/6/2023 16:06:46,4,2,1,1,Yes,Arts & Media
247,9/27/2023 14:36:39,4,4,4,5,Yes,"Science, Engineering, & Technology"
248,9/30/2023 14:50:40,3,2,2,1,Yes,Business
249,10/12/2023 11:59:11,3,2,2,2,Yes,"Science, Engineering, & Technology"
250,10/13/2023 14:29:10,4,3,2,3,Yes,"Science, Engineering, & Technology"
251,10/18/2023 10:33:47,4,4,4,4,Yes,"Science, Engineering, & Technology"
252,10/19/2023 12:45:29,3,2,3,2,Yes,"Science, Engineering, & Technology"
253,10/24/2023 14:02:44,5,2,3,3,Yes,"Science, Engineering, & Technology"
254,10/24/2023 14:22:30,4,3,2,2,Yes,Arts & Media
255,10/25/2023 10:08:07,4,3,3,2,Yes,"Science, Engineering, & Technology"
256,11/6/2023 8:52:21,4,3,2,2,Yes,"Science, Engineering, & Technology"
257,1/25/2024 14:51:11,4,2,2,2,Yes,"Science, Engineering, & Technology"

In [24]:
#Take a sample from students who uses artificial intelligence for personal use
aiUse = dataFrame.iloc[:,2]
sample = aiUse[:20]

0     5
1     3
2     3
3     3
4     2
5     1
6     1
7     2
8     3
9     2
10    1
11    2
12    2
13    1
14    1
15    2
16    2
17    1
18    2
19    3
Name: On a scale from 1 to 5, how often do you use Artificial Intelligence (AI) for personal use?, dtype: int64

In [25]:
#Tally the number of ratings
sampleCounts = sample.value_counts()
print(sampleCounts)

2    8
1    6
3    5
5    1
Name: On a scale from 1 to 5, how often do you use Artificial Intelligence (AI) for personal use?, dtype: int64

In [30]:
#Multiply two columns
sampleCountsDf = sampleCounts.reset_index()
sampleCountsDf.columns=['rating', 'choices']

sampleCountsDf['multiplier'] = sampleCountsDf['rating'] * sampleCountsDf['choices']
print(sampleCountsDf)

   rating  choices  multiplier
0       2        8          16
1       1        6           6
2       3        5          15
3       5        1           5

In [32]:
#Take the mean average of the people who uses Artificial intelligence for personal use
def findMean(sampleCountsDf):
  mean = stat.mean(sampleCountsDf['multiplier'])
  return mean

print(findMean(sampleCountsDf))

10.5

In [38]:
#Take a sample of 20 from people who uses Artificial intelligence for school use

aiUse = dataFrame.iloc[:,3]
sample = aiUse[:20]
sample

0     5
1     4
2     5
3     5
4     1
5     1
6     1
7     1
8     3
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    2
19    3
Name: On a scale from 1 to 5, how often do you use Artificial Intelligence (AI) for school-related tasks?, dtype: int64